### ISSUE TITLE
A way to inject a service which is declared as a part of a complex module.

### ISSUE THREAD

**Issue by franza** [gobwas/dm.js#36]
Hey there, I'd like to use dm.js in my development but I have a question. Assume, you are in NodeJS and you have a class:

```javascript
// models.js
function Person () { /* ... */ }
// ... here go the declarations of other classes
```

And it is exported as a property of a module:

```javascript
// models.js
module.exports = {
  Person: require('./person'),
  // ... here go some other classes
}
```
How will you register the instance of `Person` in this case? If config looks like:
```javascript
var config = {
  "person": {
    "path": "???"
  }
```
What should be specified in `path` property? Is there a way to specify a property of module?

**Comment by gobwas** [comment]
Hello!

Looks like right now it cannot be solved any way.

But this feature looks like really useful.

How do you think it could be declared in config? I can implement it soon.

First thoughts is to write new `Loader` class, that will be keep this logic.

**Comment by franza** [comment]
Smth like this maybe:
```javascript
var config = {
  "person": {
    "path": "path/to/module#property1.property2.property3"
  }
};
```
or use some kind of JSONPath here:
```javascript
var config = {
  "person": {
    "path": "path/to/module",
    "jsonPath": "$.property1.property2.property3"
  }
};
```
Also, need to consider the fact that if no property was passed, then use the old logic (one module - one class). What do you think?

P.S. Is there a way to resolve dependencies synchronously?

**Comment by gobwas** [comment]
I think the first case is a good one. But I was planned to do this via [JSON Pointer](https://tools.ietf.org/html/rfc6901). And the second but - is that we need to add ability also require by module names, like:

```js
{
  "emitter": {
    "path": "events#EventEmitter"
  }
}
```

P.S. Yes, you can use `BroodyPromisesAsync` adapter. =)

**Comment by franza** [comment]
I cannot catch your second point. Can you add more details on that?

**Comment by gobwas** [comment]
I mean `CJSLoader` class receives `options` object, with optional `base` property. When he receives string to load, he try to make some `path.resolve(base, needle)`. So, if you pass just a module name, like `events` - it could become a `path/to/base/events`, if `base` option was set. =)

I think to resolve this by the checking first symbol of path to equality with `.`.

**Comment by franza** [comment]
Just to notice - the case with NODE_PATH var is set should be handled too, but I guess it is handled automatically then.

**Comment by gobwas** [comment]
Hey @franza, just released RC version now.

You could install it via:

```shell
npm install dm@0.3.1-rc
```

Use with this [RFC](https://tools.ietf.org/html/rfc6901).

Will release 0.3.1 soon if there is no errors. 

Thanks!

**Comment by franza** [comment]
That's great! Btw, what's the syntax to use?

**Comment by gobwas** [comment]
Smth like:

```js
// path/to/my/module.js
module.exports = {
  field: function Ctor() {...}
}

{
  path: "path/to/my/module.js#/field"
}
```

**Comment by gobwas** [comment]
Is it OK? )

**Comment by franza** [comment]
Nope, `npm install dm@0.3.1-rc` doesn't work for me

**Comment by gobwas** [comment]
`0.3.1-rc` is a npm tag, you could use it instead of `npm install dm@latest`, like: `npm install dm@0.3.1-rc`. In package.json you should use ```"dm": "0.3.1-rc0"``` - with concrete version number =)

**Comment by franza** [comment]
Argh, so it is `npm install dm@0.3.1-rc0`

**Comment by gobwas** [comment]
Yes, at my home npm with oldest version it worked =) Now tags [must be not a semver like](https://github.com/npm/npm/issues/6082) =(

**Comment by franza** [comment]
Ok, that worked for new and new feature works great. Thank you very much.

I also have a question about instantiating objects. So assume that you don't use a constructor and `new` word, but use plain old functions:

```javascript
function getMySQLConfigs() {
  return { /* ... */ };
}
```
Is it supported in dm.js?

**Comment by gobwas** [comment]
There is some [issue](https://github.com/gobwas/dm.js/issues/35) for that puproses. Fell free to comment and improve an idea.
