### ISSUE TITLE
Is there a way to collect results without handling promises?

### ISSUE THREAD

**Issue by franza** [gobwas/dm.js#38]
I am going to use dm.js in NodeJS application. I am going to resolve dependencies on the application level and I don't see any reasons to have dependencies resolved asynchronously.

Is there any way to use dm.js without bringing promises? Something like:
```javascript
var logger = dm.get('logger');
```
instead of
```javascript
dm.get('logger').then(function (logger) { /* ... */ });
```
If not, can you please provide an example of using dm.js with BroodyPromisesAsync ?

**Comment by gobwas** [comment]
There are two ways of doing this.

First, and, in my opinion, the most architecture clear - is to use dm not like service locator (when you always ask for concrete dependency, like in your example). You can define the main module, which you configure to use for your needs:

```js
// config.js
module.exports = {
  "app": {
    "path": "...",
    "calls": [
      ["injectActorA", ["@actor"]],
      ["injectActorB", ["@actor.b"]]
    ]
  },

  "actor": {
    "path": "...",
    "calls": [
      ["injectLogger", ["@logger"]]
    ]
  }
}
```

```js
// app.js

module.exports = function App() {

}

App.prototype.injectActor: function(actor) {
  this.actor = actor;
}

App.prototype.run = function() {
  // do necessary things here, for example
  var self = this;
  server.listen(8080, function(req, res) {
    self.actor
      .handle(req)
      .then(function(resp){ res.write(resp); res.end() });
  });
}
```

```js
// app.js

dm.get("app").theh(function(app) {
  app.run();
});
```

**Comment by franza** [comment]
Using it as service locator wasn't my intent actually. I'm just messing around with several DInj libraries here and there trying to find best for project I'm involved.

Broodys actually looks good, but I think I have issues with making it work with my test example. Looks like the dependencies that I pass into the Logger constructor are still unresolved Promises but not values:

```javascript
function Logger(formatter, config) {
    this.formatter_ = formatter;
    this.config_ = config;
}

Logger.prototype.log = function (message) {
    console.log(this.config_.filename + ' - ' + this.formatter_.format(message));
};
// in composition root
var DM     = require("dm"),
    Loader = require("dm/lib/loader/cjs"),
    BroodyPromisesAsync = require("dm/lib/async/broody"),
    BroodyPromises      = require("broody-promises"),
    dm;

dm = new DM(new BroodyPromisesAsync(BroodyPromises), new Loader(require), {
    parameters: {
        "config": { "filename": __filename }
    },

    services: {
        "timeLogger": {
            "path": "./logger.js",
            "arguments": ["@timeFormatter", "%config%"]
        },

        "caseLogger": {
            "path": "./logger.js",
            "arguments": ["@caseFormatter", "%config%"]
        },

        "timeFormatter": {
            "path": "./formatters/time_formatter.js"
        },

        "caseFormatter": {
            "path": "./formatters/case_formatter.js"
        },
    }
});

var timeLogger = dm.get('timeLogger').done();
var caseLogger = dm.get('caseLogger').done();

timeLogger.log("Hello! It works!"); // this throws exception since formatter is still a promise and it does not have method "format"
```

**Comment by gobwas** [comment]
Hey there!

Thank you for your test project. Ive checked it out, and found a bug inside BroodyPromises. Will fix it very soon (hope today, or tomorrow). With your idea with JSONPointer.

Thanks a lot )

**Comment by gobwas** [comment]
@franza just released new version of Broodys, check them out =) 
Your code should work now )

**Comment by franza** [comment]
That worked!! Many thanks :)

**Comment by gobwas** [comment]
If you want, you can use a [Bluebird]() promises, which is also have `value()` method, similar to `.done()` in Broodys. All you need is to write simple `BluebirdAsyncAdapter`. If you want - PR it =)
